### ISSUE TITLE
Large Icons in 'about me' section

### ISSUE THREAD

**Issue by ZloiY** [Terenfear/react-portfolio#12]
I had just a regular morning when I was surfing web in safari and enjoining myself before I encountered your website(that's another deal, if u ask me). And the website looks pretty and smooth, but then I saw this 
<img width="2056" alt="Screenshot 2021-12-03 at 10 23 03" src="https://user-images.githubusercontent.com/15103948/144562772-64d97f86-30fe-4d63-bed2-f1263706d13d.png">
After that my day was ruined. Imagine my shock, just a moment ago I was browsing websites on my new fresh macbook pro with m1 pro and then I look at this ugly bloated piece of vector graphics that takes half of my pro retina xdr liquid display. So can you fix this "issue"(more like a big problem). Looks okay thou on chromium based trash and firefox.

**Comment by Terenfear** [comment]
Oh no, I'm so terribly sorry! A fine wealthy technologically advanced gentleman such as yourself don't have to stand this crap. I can only hope that your magnificent laptop won't decide to suicide after such a horrible web site. Considering that you know where I live, I have take precautions and weld off my front door, just to be sure that you won't come busting on here demanding a bloody revenge.

In the mean time I'll take a look at this issue (after assigning and re-assigning myself a couple more times, I guess)

**Comment by Terenfear** [comment]
I tested stuff using online cross-browser testing tools and it like I've managed to fix this. Please, take a look using your amazing laptop.
